DECK_CREATE = "/api/decks/create"
DECK_UPDATE = "/api/decks/update/{deck_id:uuid}"
DECK_DELETE = "/api/decks/delete/{deck_id:uuid}"
DECK_LIST = "/api/decks"
DECK_GET = "/api/decks/{deck_id:uuid}"
DECK_ADD_CARD = "/api/decks/add_card"

CARD_CREATE = "/api/cards/create"
CARD_UPDATE = "/api/cards/update/{card_id:uuid}"
CARD_DELETE = "/api/cards/delete/{card_id:uuid}"
CARD_LIST = "/api/cards"
CARD_GET = "/api/cards/{card_id:uuid}"
CARD_ADD_TAG = "/api/cards/add_tag"

TAG_CREATE = "/api/tags/create"
TAG_UPDATE = "/api/tags/update/{tag_id:uuid}"
TAG_DELETE = "/api/tags/delete/{tag_id:uuid}"
TAG_LIST = "/api/tags"
TAG_GET = "/api/tags/{tag_id:uuid}"
